import type { Metadata } from "next"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import CampaignListWrapper from "@/components/Context"

export const metadata: Metadata = {
  title: "Slyce Assignment Solution",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <CampaignListWrapper>
            {children}
          </CampaignListWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
